version: "3.8"
services:
  soda-core-db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - "50000:50000"
    volumes:
      - ./.db2/:/database
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=testdb
